### ISSUE TITLE
Renaming the library

### ISSUE THREAD

**Issue by Malharhak** [Malharhak/fmath.js#9]
I was contacted by someone holding a trademark on the "SMath" name ([SMath Studio](http://en.smath.info/)) which means I have to rename this project.

I think the easiest would be to just name it OMath (for Optimized Maths, instead of Speed Maths. That still works).

I will probably also rename the class for coherence with the name, meaning old code might break. I will also keep the old version in a branch just in case

**Comment by dbkaplun** [comment]
How about fmath for "Fast Math"?

**Comment by Malharhak** [comment]
OMath seems largely used too, so yea fmath would be better. I'll create the branch

**Comment by Malharhak** [comment]
updating the code and package info in the branch to reflect the name change
